// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbpzpktreehmleglmfqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicHpwa3RyZWVobWxlZ2xtZnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODg3MzEsImV4cCI6MjA2ODk2NDczMX0._UnmS59pH_kHrjSWH9MY7esGLLvoS2xlPf4TUNFv_OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});